<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AI Pulse</AssemblyName>
    <RootNamespace>AIPulse</RootNamespace>
    <Version>1.2.0-experimental.1</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <InformationalVersion>1.2.0-experimental.1</InformationalVersion>
    <Company>miaomiao tools</Company>
    <Authors>miaomiao tools</Authors>
    <Product>AI Pulse</Product>
    <Copyright>Copyright (c) 2026 miaomiao tools</Copyright>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <PathMap>$(MSBuildProjectDirectory)=/_/src,$(BaseIntermediateOutputPath)=/_/obj</PathMap>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeFrameworkVersion>8.0.31</RuntimeFrameworkVersion>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <RestoreIgnoreFailedSources>false</RestoreIgnoreFailedSources>
  </PropertyGroup>
  <ItemGroup><Resource Include="app.ico"/></ItemGroup>
</Project>
